USE CookFlow;
GO


CREATE OR ALTER PROCEDURE SP_GetFavoritosUsuario @USid INT AS
BEGIN
    SET NOCOUNT ON;
    SELECT r.RECid, r.RECtitulo, r.RECdescripcion, r.RECimagen,
           r.RECtiempo, r.RECdificultad, r.CAid, f.FRfecha
    FROM FAVORITOS_RECETAS f
    JOIN RECETAS r ON r.RECid = f.RECid
    WHERE f.USid = @USid
    ORDER BY f.FRfecha DESC;
END
GO

CREATE OR ALTER PROCEDURE SP_InsertFavorito @USid INT, @RECid INT AS
BEGIN
    SET NOCOUNT ON;
    INSERT INTO FAVORITOS_RECETAS (USid, RECid) VALUES (@USid, @RECid);
END
GO

CREATE OR ALTER PROCEDURE SP_DeleteFavorito @USid INT, @RECid INT AS
BEGIN
    SET NOCOUNT ON;
    DELETE FROM FAVORITOS_RECETAS WHERE USid = @USid AND RECid = @RECid;
    SELECT @@ROWCOUNT AS filas;
END
GO