USE CookFlow;
GO


CREATE OR ALTER PROCEDURE SP_GetRecetaById @RECid INT
AS BEGIN
    SET NOCOUNT ON;
    SELECT * FROM RECETAS WHERE RECid = @RECid;
END
GO

CREATE OR ALTER PROCEDURE SP_UpdateReceta
    @RECid INT, @titulo VARCHAR(150), @descripcion VARCHAR(MAX),
    @imagen VARCHAR(255), @tiempo INT, @dificultad VARCHAR(50), @CAid INT
AS BEGIN
    SET NOCOUNT ON;
    UPDATE RECETAS
    SET RECtitulo = @titulo, RECdescripcion = @descripcion, RECimagen = @imagen,
        RECtiempo = @tiempo, RECdificultad = @dificultad, CAid = @CAid
    WHERE RECid = @RECid;
    SELECT @@ROWCOUNT AS filas;
END
GO

CREATE OR ALTER PROCEDURE SP_DeleteReceta @RECid INT
AS BEGIN
    SET NOCOUNT ON;
    BEGIN TRY
        BEGIN TRANSACTION;
        DELETE FROM FAVORITOS_RECETAS    WHERE RECid = @RECid;
        DELETE FROM RECETA_INGREDIENTES  WHERE RECid = @RECid;
        DELETE FROM RECETAS              WHERE RECid = @RECid;
        DECLARE @filas INT = @@ROWCOUNT;
        COMMIT TRANSACTION;
        SELECT @filas AS filas;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        THROW;
    END CATCH
END
GO

CREATE OR ALTER PROCEDURE SP_UpdateIngredienteReceta
    @RECid INT, @INid INT, @cantidad DECIMAL(10,2), @unidad VARCHAR(50)
AS BEGIN
    SET NOCOUNT ON;
    UPDATE RECETA_INGREDIENTES SET RIcantidad = @cantidad, RIunidad = @unidad
    WHERE RECid = @RECid AND INid = @INid;
    SELECT @@ROWCOUNT AS filas;
END
GO

CREATE OR ALTER PROCEDURE SP_DeleteIngredienteReceta @RECid INT, @INid INT
AS BEGIN
    SET NOCOUNT ON;
    DELETE FROM RECETA_INGREDIENTES WHERE RECid = @RECid AND INid = @INid;
    SELECT @@ROWCOUNT AS filas;
END
GO


CREATE OR ALTER PROCEDURE SP_GetCategorias AS
BEGIN SET NOCOUNT ON; SELECT * FROM CATEGORIAS ORDER BY CAnombre; END
GO
CREATE OR ALTER PROCEDURE SP_GetCategoriaById @CAid INT AS
BEGIN SET NOCOUNT ON; SELECT * FROM CATEGORIAS WHERE CAid = @CAid; END
GO
CREATE OR ALTER PROCEDURE SP_InsertCategoria @nombre VARCHAR(100), @descripcion VARCHAR(255) = NULL AS
BEGIN
    SET NOCOUNT ON;
    INSERT INTO CATEGORIAS (CAnombre, CAdescripcion) VALUES (@nombre, @descripcion);
    SELECT SCOPE_IDENTITY() AS id;
END
GO
CREATE OR ALTER PROCEDURE SP_UpdateCategoria @CAid INT, @nombre VARCHAR(100), @descripcion VARCHAR(255) = NULL AS
BEGIN
    SET NOCOUNT ON;
    UPDATE CATEGORIAS SET CAnombre = @nombre, CAdescripcion = @descripcion WHERE CAid = @CAid;
    SELECT @@ROWCOUNT AS filas;
END
GO
CREATE OR ALTER PROCEDURE SP_DeleteCategoria @CAid INT AS
BEGIN
    SET NOCOUNT ON;
    DELETE FROM CATEGORIAS WHERE CAid = @CAid;   
    SELECT @@ROWCOUNT AS filas;
END
GO


CREATE OR ALTER PROCEDURE SP_GetIngredientes @buscar VARCHAR(100) = NULL AS
BEGIN
    SET NOCOUNT ON;
    SELECT * FROM INGREDIENTES
    WHERE @buscar IS NULL OR INnombre LIKE '%' + @buscar + '%'
    ORDER BY INnombre;
END
GO
CREATE OR ALTER PROCEDURE SP_GetIngredienteById @INid INT AS
BEGIN SET NOCOUNT ON; SELECT * FROM INGREDIENTES WHERE INid = @INid; END
GO
CREATE OR ALTER PROCEDURE SP_InsertIngrediente @nombre VARCHAR(100) AS
BEGIN
    SET NOCOUNT ON;
    INSERT INTO INGREDIENTES (INnombre) VALUES (@nombre);
    SELECT SCOPE_IDENTITY() AS id;
END
GO
CREATE OR ALTER PROCEDURE SP_UpdateIngrediente @INid INT, @nombre VARCHAR(100) AS
BEGIN
    SET NOCOUNT ON;
    UPDATE INGREDIENTES SET INnombre = @nombre WHERE INid = @INid;
    SELECT @@ROWCOUNT AS filas;
END
GO
CREATE OR ALTER PROCEDURE SP_DeleteIngrediente @INid INT AS
BEGIN
    SET NOCOUNT ON;
    DELETE FROM INGREDIENTES WHERE INid = @INid;  -- falla (547) si está en recetas o listas
    SELECT @@ROWCOUNT AS filas;
END
GO


CREATE OR ALTER PROCEDURE SP_InsertRestaurante
    @nombre VARCHAR(100), @direccion VARCHAR(255) = NULL, @tipo VARCHAR(100) = NULL AS
BEGIN
    SET NOCOUNT ON;
    INSERT INTO RESTAURANTES (RESnombre, RESdireccion, REStipo) VALUES (@nombre, @direccion, @tipo);
    SELECT SCOPE_IDENTITY() AS id;
END
GO
CREATE OR ALTER PROCEDURE SP_GetRestaurantes AS
BEGIN SET NOCOUNT ON; SELECT * FROM RESTAURANTES ORDER BY RESnombre; END
GO
CREATE OR ALTER PROCEDURE SP_GetRestauranteById @RESid INT AS
BEGIN SET NOCOUNT ON; SELECT * FROM RESTAURANTES WHERE RESid = @RESid; END
GO
CREATE OR ALTER PROCEDURE SP_UpdateRestaurante
    @RESid INT, @nombre VARCHAR(100), @direccion VARCHAR(255) = NULL, @tipo VARCHAR(100) = NULL AS
BEGIN
    SET NOCOUNT ON;
    UPDATE RESTAURANTES SET RESnombre = @nombre, RESdireccion = @direccion, REStipo = @tipo
    WHERE RESid = @RESid;
    SELECT @@ROWCOUNT AS filas;
END
GO
CREATE OR ALTER PROCEDURE SP_DeleteRestaurante @RESid INT AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRY
        BEGIN TRANSACTION;
        DELETE FROM RESTAURANTES_VISITADOS WHERE RESid = @RESid;
        DELETE FROM RESTAURANTES WHERE RESid = @RESid;
        DECLARE @filas INT = @@ROWCOUNT;
        COMMIT TRANSACTION;
        SELECT @filas AS filas;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        THROW;
    END CATCH
END
GO

CREATE OR ALTER PROCEDURE SP_GetUsuarios AS
BEGIN SET NOCOUNT ON; SELECT USid, USnombre, USemail, USfechaalta FROM USUARIOS; END
GO
CREATE OR ALTER PROCEDURE SP_GetUsuarioById @USid INT AS
BEGIN SET NOCOUNT ON; SELECT USid, USnombre, USemail, USfechaalta FROM USUARIOS WHERE USid = @USid; END
GO
CREATE OR ALTER PROCEDURE SP_GetUsuarioByEmail @email VARCHAR(100) AS
BEGIN SET NOCOUNT ON; SELECT * FROM USUARIOS WHERE USemail = @email; END
GO
CREATE OR ALTER PROCEDURE SP_UpdateUsuario @USid INT, @nombre VARCHAR(100), @email VARCHAR(100) AS
BEGIN
    SET NOCOUNT ON;
    UPDATE USUARIOS SET USnombre = @nombre, USemail = @email WHERE USid = @USid;
    SELECT @@ROWCOUNT AS filas;
END
GO
CREATE OR ALTER PROCEDURE SP_DeleteUsuario @USid INT AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRY
        BEGIN TRANSACTION;
        DELETE FROM FAVORITOS_RECETAS WHERE USid = @USid;
        DELETE FROM RESTAURANTES_VISITADOS WHERE USid = @USid;
        DELETE FROM LISTA_COMPRA_ITEMS WHERE LCid IN (SELECT LCid FROM LISTA_COMPRA WHERE USid = @USid);
        DELETE FROM LISTA_COMPRA WHERE USid = @USid;
        -- Sus recetas (y lo que cuelga de ellas)
        DELETE FROM FAVORITOS_RECETAS   WHERE RECid IN (SELECT RECid FROM RECETAS WHERE USid = @USid);
        DELETE FROM RECETA_INGREDIENTES WHERE RECid IN (SELECT RECid FROM RECETAS WHERE USid = @USid);
        DELETE FROM RECETAS WHERE USid = @USid;
        DELETE FROM USUARIOS WHERE USid = @USid;
        DECLARE @filas INT = @@ROWCOUNT;
        COMMIT TRANSACTION;
        SELECT @filas AS filas;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        THROW;
    END CATCH
END
GO

CREATE OR ALTER PROCEDURE SP_UpdateVisita
    @USid INT, @RESid INT, @puntuacion INT = NULL, @comentario VARCHAR(500) = NULL AS
BEGIN
    SET NOCOUNT ON;
    UPDATE RESTAURANTES_VISITADOS SET RVpuntuacion = @puntuacion, RVcomentario = @comentario
    WHERE USid = @USid AND RESid = @RESid;
    SELECT @@ROWCOUNT AS filas;
END
GO
CREATE OR ALTER PROCEDURE SP_DeleteVisita @USid INT, @RESid INT AS
BEGIN
    SET NOCOUNT ON;
    DELETE FROM RESTAURANTES_VISITADOS WHERE USid = @USid AND RESid = @RESid;
    SELECT @@ROWCOUNT AS filas;
END
GO